name: Git Action Echo result.

# Only run on a push to this branch
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Step 1
              run: echo "Testing my Git Action Workflow."


