name: Git Action Echo result.

# Only run on a push to this branch
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Step 1
              run: echo "Testing my Git Action Workflow."
            - uses: actions/checkout@v2
            - name: Listing Repo
              run: |
                  pwd
                  ls
            - name: Clean project
              run: |
                  pwd
                  ls
                  git status
                  git branch
                  git log --format="Github Sync: %an : %s" -n 1             


